# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/235b08e0-7b95-424e-819b-b7a9cd30b787";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/235b08e0-7b95-424e-819b-b7a9cd30b787";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/235b08e0-7b95-424e-819b-b7a9cd30b787";
    fsType = "btrfs";
    options = [ "subvol=@var" ];
  };

  fileSystems."/.swap" = {
    device = "/dev/disk/by-uuid/235b08e0-7b95-424e-819b-b7a9cd30b787";
    fsType = "btrfs";
    options = [ "subvol=@swap" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/235b08e0-7b95-424e-819b-b7a9cd30b787";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/2fec6825-668e-41e1-aec4-caa1d658b0a3";
    fsType = "btrfs";
  };

  fileSystems."/backup" = {
    device = "/dev/disk/by-uuid/03a56055-1801-4c1e-bc64-17f3d1889a44";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/930C-4450";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
